### ISSUE TITLE
Support for Flaxbeard's Cyberware / WIRED

### ISSUE THREAD

**Issue by 4rz0** [M4thG33k/TombManyGraves#17]
I suggest adding support for Flaxbeard's Cyberware and the addon-mod WIRED: More Augs, so that on death, installed augments are placed inside the grave instead of plopping into the world.

**Comment by M4thG33k** [comment]
I'll try to take a look at it tomorrow (unless something comes up with work)

**Comment by M4thG33k** [comment]
Adding support for this is still on my To-do list. I'll hopefully get around to adding it next week.

**Comment by 4rz0** [comment]
@M4thG33k Don't stress yourself ;D

**Comment by M4thG33k** [comment]
After taking a look at the mod, I've decided not to add compatibility with Tomb Many Graves. Since the original mod doesn't allow you to get your augmentations back upon death, I think it would be a little OP for the grave to hold on to them and give them back. I don't want to break another person's mod.

**Comment by 4rz0** [comment]
Fair enough.
I'll consider this resolved then.
