### ISSUE TITLE
Grave so large it crashes anyone near it

### ISSUE THREAD

**Issue by Luckdemon** [M4thG33k/TombManyGraves#40]
I believe that a player was dying everytime he /back'ed to his death point so many times that his death list contained lists of the previous lists in a very deep loop, enough so that it caused his grave data to overflow and crash anyone loading that block.
Error as it shows up to players: http://i.imgur.com/JQeOP1c.png
Grave file is too large to upload, but I can cut it in pieces or send it to you some other way, the largest file is 460KB, and it appears that every time this player died, his grave size doubled. 
picture of file sizes and datestamps on the graves: http://puu.sh/t3aQB/860f377f81.png
This user died 27 times in the span of 2 hours, and 46 times in the span of 6 hours.
If you need any other information, let me know.
Another picture of most of his deaths with filesizes and timestamps: http://puu.sh/t3aX0/de0175f6a3.png
It appears that every death without dropping or deleting the death list roughly doubles the size of the grave.

**Comment by M4thG33k** [comment]
I should have realized this was going to be a problem sooner. I'll add a fix (not allowing death lists to be captured by the grave) when I get back home next week. 

The /tmg_loot command may be able to restore the player's grave and remove the grave from the world. (Make sure the player's inventory is empty beforehand, because I wrote that command to be a last resort so it may overwrite their current inventory). Otherwise, you'll have to use the vanilla command to set the graves to air (and manually delete the corresponding item list files to keep players from attempting to spawn them in again). 

If you need more info or have issues with any of this, please let me know. Thanks!

**Comment by Luckdemon** [comment]
Just an odd thing, it wouldn't let me set it to air, I had to set it to stone. But it's all fixed now, thanks. :) I was rather surprised to see that lists got captured in the graves.

**Comment by M4thG33k** [comment]
This will be fixed in the next update. Thanks again for letting me know about this issue!
