### ISSUE TITLE
Incompatibility With Natural Pledge

### ISSUE THREAD

**Issue by gr8pefish** [M4thG33k/TombManyGraves#41]
The Return Stone apparently conflicts with this mod.

I believe you simply need to turn down your event priority to fix this.

CC'ing @yrsegal for clarification.

**Comment by yrsegal** [comment]
You're catching drops before other mods can edit them. Dropping the
priority of your @SubscribeEvent to LOWEST should work.

**Comment by M4thG33k** [comment]
@yrsegal I'm not going to be able to drop it all the way to lowest; I can drop it down to LOW though. I believe I still need to be one priority above Iron Backpacks in order for compatibility with the eternity upgrade to work; that's what we decided, right @gr8pefish?

**Comment by yrsegal** [comment]
Nothing should be at LOWEST on a drop event unless it plans to catch-all.
That would be a mistake on Iron Backpacks' end. NORMAL is for things like
Resolute Ivy, The Stone of Return, Soulbound items, and the like.

**Comment by M4thG33k** [comment]
How exactly does the return stone work? It looks like it gathers the player's coordinates on death and then stays in the player's inventory? If so, I can just have the grave blacklist that item so it doesn't attempt to be gathered in.

**Comment by yrsegal** [comment]
It takes itself out of the inventory on NORMAL and adds it to the new
instance of the player. Blacklisting it, while imperfect, would work. A
more permanent and encompassing solution would be preferred, though.

**Comment by M4thG33k** [comment]
I haven't found a good way to have the grave keep its replacement property while conforming to the standard of other grave mods (since the drop-item event doesn't keep track of what slot from which it was dropped), so I have to default to adding compatibility for every mod that adds special behavior. The next iteration of the mod should include a config for items to blacklist from graves to make this sort of compatibility a tad bit easier.

**Comment by yrsegal** [comment]
Oh, that makes sense. I hadn't considered that the drops might not exist
with their slots in a useful manner. The config seems the best solution.

**Comment by gr8pefish** [comment]
I agree, a config seems like a good middle ground here. I believe my soulbound equivalent is at NORMAL priority now, though I'd have to check my source code to be sure.

**Comment by M4thG33k** [comment]
The next update will include the blacklist feature and will default to including this stone.

On a side note, I was actually planning to add a feature similar to what the stone does to the death list from TMG (since they already inherently store the grave's location). Do you have any problem with me referencing your code for that, @yrsegal?

**Comment by yrsegal** [comment]
No, go right ahead. Do be warned it's in kotlin, though... 😅

**Comment by M4thG33k** [comment]
I noticed it wasn't java, but that shouldn't be an issue. :-) It's just easier to work off something that already exists (and works). Thanks!
