### ISSUE TITLE
Can't pick up grave when died on lava; Craft of the Titans

### ISSUE THREAD

**Issue by hrstruggle** [M4thG33k/TombManyGraves#51]
Hello,

I died after getting shoved into lava by mob.  I've been able to isolate the grave block so I can sneak over it safely but I can't pick up block.

I notice that I can shift-click and it changes the text above the grave and I'm not sure what that means.  See links for screenshots.

https://imgur.com/DoiMyC5
https://imgur.com/hIIOosM

Really, I just want to be able to pick up my stuff.  It's possible there may be another grave below it but I'm not sure - just mentioning in case that has something to do with it.

Any solutions to pick up my things from grave?

Thanks, Howard (hrstruggle)

**Comment by M4thG33k** [comment]
It looks like the grave is in "locked" mode which prevents accidental gathering of the grave (indicated by the skull being almost flush with the block instead of peaking out of the grave). Right clicking (or shift-right clicking) should toggle between the two states (I'm assuming it's just normal right-clicking since you've mentioned that shift-clicking changes the mode of the grave: swap will always put items back in their original slots regardless of what currently occupies those slots (throwing the original items on the ground) where non-swap mode only puts items in their original slots if they are empty.)

If you're unable to unlock the grave, let me know and I'll try to remember the op commands for getting your items back to you. :-)

**Comment by hrstruggle** [comment]
Thanks for quick reply. Still not clear how to unlock it.

**Comment by M4thG33k** [comment]
Try right clicking. If that doesn't work, try sneaking while right clicking.

**Comment by hrstruggle** [comment]
Neither works.

**Comment by hrstruggle** [comment]
Right-clicking switches between swap and non-swap. Sneaking does nothing.

**Comment by M4thG33k** [comment]
Weird. Which version is this in?

**Comment by hrstruggle** [comment]
1.10.2-2.1.16

**Comment by M4thG33k** [comment]
Very weird. The code shows that sneaking/right clicking will work. Since that's not the case, if you're able to use commands, try using the /tmg_loot command (it has in-game help if you type it)

**Comment by hrstruggle** [comment]
It says I don't have permissions to use that command.  Do I need to do this in creative mode or op myself?  Not having luck with either in Craft of the Titans.  Ugh.  Sorry to be a PITA.

**Comment by M4thG33k** [comment]
You'll need to be op-ed in order to use the command, yes. If that doesn't work, then I have to assume there is another mod causing compatibility issues. :-/

**Comment by hrstruggle** [comment]
Thanks.  /tmg_loot worked.
