### ISSUE TITLE
Baubles drop on death.

### ISSUE THREAD

**Issue by JosEffigy** [M4thG33k/TombManyGraves#7]
Baubles 1.2.1.0
Botania Unofficial r1.8-111
Tomb Many Graves 1.10-3.0.0

Botania Unofficial's Baubles drop on death.

**Comment by M4thG33k** [comment]
Yeah, I disabled the Baubles support when I released the 1.10 version of the mod to allow the other mods to release/update their versions to 1.10. I will re-enable this feature (and cosmetic armor's) in the next build.

**Comment by psychofad** [comment]
Was this ever fixed?  If so which version has the fix?  There appears to be a TombManyGraves for 1.10 that is version 3.0 and then you went back to using the 1.9.4 format but listed it as being compatible with 1.10.2 but there is no mention of this being re-enabled in the changelog for that version.

**Comment by M4thG33k** [comment]
After realizing that one version of TMG works for versions 1.9.4+, I will only be maintaining one version (the most recent one). Since version TombManyGraves-1.9.4-2.1.6 does work for all three versions, it is compatible with both Baubles and Cosmetic Armor (since all 1.9.4 versions are). Sorry for not making it clear in the change logs when this happened. I'll try to do better with this in the future.
